### ISSUE TITLE
Watch mode errors with '<package-1/every-file>' is not under 'rootDir' for package-2

### ISSUE THREAD

**Issue by cormacrelf** [alan-agius4/ng-mono-repo-starter#53]
Repro:

```sh
# clone, yarn ...
yarn watch
```

Result: see below. When building package-2, ngc is somehow only getting paths that have already been transformed through the tsconfig.

* * *

```
yarn run v1.7.0
$ set WATCH_MODE=true&& lerna exec --concurrency=1 --parallel node ../../tools/tasks/build
@speedy/package-2: Building Angular Package
@speedy/package-1: Building Angular Package
@speedy/package-2: Building entry point '@speedy/package-2'
@speedy/package-2: Compiling TypeScript sources through ngc
@speedy/package-1: Building entry point '@speedy/package-1'
@speedy/package-1: Compiling TypeScript sources through ngc
@speedy/package-2: BUILD ERROR
@speedy/package-2: error TS6059: File '/Users/cormac/git/cormacrelf/monostart/packages/package-1/src/module.ts' is not under 'rootDir' '/Users/cormac/git/cormacrelf/monostart/packages/package-2'. 'rootDir' is expected to contain all source files.
@speedy/package-2: error TS6059: File '/Users/cormac/git/cormacrelf/monostart/packages/package-1/src/skeleton/skeleton.component.ts' is not under 'rootDir' '/Users/cormac/git/cormacrelf/monostart/packages/package-2'. 'rootDir' is expected to contain all source files.
@speedy/package-2: Error: error TS6059: File '/Users/cormac/git/cormacrelf/monostart/packages/package-1/src/module.ts' is not under 'rootDir' '/Users/cormac/git/cormacrelf/monostart/packages/package-2'. 'rootDir' is expected to contain all source files.
@speedy/package-2: error TS6059: File '/Users/cormac/git/cormacrelf/monostart/packages/package-1/src/skeleton/skeleton.component.ts' is not under 'rootDir' '/Users/cormac/git/cormacrelf/monostart/packages/package-2'. 'rootDir' is expected to contain all source files.
@speedy/package-2:     at Object.<anonymous> (/Users/cormac/git/cormacrelf/monostart/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
@speedy/package-2:     at Generator.next (<anonymous>)
@speedy/package-2:     at /Users/cormac/git/cormacrelf/monostart/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
@speedy/package-2:     at new Promise (<anonymous>)
@speedy/package-2:     at __awaiter (/Users/cormac/git/cormacrelf/monostart/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
@speedy/package-2:     at Object.compileSourceFiles (/Users/cormac/git/cormacrelf/monostart/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
@speedy/package-2:     at Object.<anonymous> (/Users/cormac/git/cormacrelf/monostart/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:28:32)
@speedy/package-2:     at Generator.next (<anonymous>)
@speedy/package-2:     at /Users/cormac/git/cormacrelf/monostart/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
@speedy/package-2:     at new Promise (<anonymous>)
@speedy/package-1: Bundling to FESM2015
@speedy/package-1: Bundling to FESM5
@speedy/package-1: Bundling to UMD
@speedy/package-1: Minifying UMD bundle
@speedy/package-1: Copying declaration files
@speedy/package-1: Writing package metadata
@speedy/package-1: Removing scripts section in package.json as it's considered a potential security vulnerability.
@speedy/package-1: Built @speedy/package-1
@speedy/package-1: Building entry point '@speedy/package-1/testing'
@speedy/package-1: Compiling TypeScript sources through ngc
@speedy/package-1: Bundling to FESM2015
@speedy/package-1: Bundling to FESM5
@speedy/package-1: Bundling to UMD
@speedy/package-1: Minifying UMD bundle
@speedy/package-1: Copying declaration files
@speedy/package-1: Writing package metadata
@speedy/package-1: Removing scripts section in package.json as it's considered a potential security vulnerability.
@speedy/package-1: Built @speedy/package-1/testing
@speedy/package-1: Built Angular Package!
@speedy/package-1:  - from: /Users/cormac/git/cormacrelf/monostart/packages/package-1
@speedy/package-1:  - to:   /Users/cormac/git/cormacrelf/monostart/packages/package-1/dist
@speedy/package-1: Bundling SCSS
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alan-agius4** [comment]
Prior to calling `watch` you need to call `build`. As first you need to build the sourceFiles to avoid these errors. SInce `exec` doesn't build the libraries in topological order.

https://github.com/alan-agius4/ng-mono-repo-starter/blob/master/README.md#npm-tasks

**Comment by cormacrelf** [comment]
I should have noted that I did call build first. Problem persists.

**Comment by alan-agius4** [comment]
Thanks for trying this project out. 

Your issue has been solved https://github.com/alan-agius4/ng-mono-repo-starter/pull/54

**Comment by cormacrelf** [comment]
Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
